import { movieImages } from './movie-images';

export type Movie = { id: string; title: string; original: string; year: number; rating: number; genres: string[]; director: string; duration: string; description: string; quote?: string; poster: string; backdrop?: string };
const entries: Omit<Movie, 'poster' | 'backdrop'>[] = [
 { id: 'inception', title: 'Incepcja', original: 'Inception', year: 2010, rating: 8.4, genres: ['Sci-Fi', 'Akcja', 'Thriller'], director: 'Christopher Nolan', duration: '2 godz. 28 min', description: 'Dom Cobb potrafi kraść tajemnice z ludzkiej podświadomości. Tym razem musi dokonać czegoś niemożliwego: zaszczepić w umyśle nową ideę.', quote: '„Twój umysł jest miejscem zbrodni.”' },
 { id: 'dark-knight', title: 'Mroczny Rycerz', original: 'The Dark Knight', year: 2008, rating: 8.5, genres: ['Akcja', 'Kryminał', 'Dramat'], director: 'Christopher Nolan', duration: '2 godz. 32 min', description: 'Batman, porucznik Gordon i Harvey Dent próbują oczyścić Gotham z przestępczości. Ich plany burzy nieprzewidywalny Joker.' },
 { id: 'dark-knight-rises', title: 'Mroczny Rycerz Powstaje', original: 'The Dark Knight Rises', year: 2012, rating: 8, genres: ['Akcja', 'Thriller', 'Dramat'], director: 'Christopher Nolan', duration: '2 godz. 44 min', description: 'Osiem lat po zniknięciu Batmana Gotham staje w obliczu nowego zagrożenia. Bruce Wayne musi powrócić, by zmierzyć się z Bane’em.' },
 { id: 'joker', title: 'Joker', original: 'Joker', year: 2019, rating: 8.2, genres: ['Dramat', 'Kryminał', 'Thriller'], director: 'Todd Phillips', duration: '2 godz. 2 min', description: 'Arthur Fleck, samotny komik z Gotham, próbuje znaleźć swoje miejsce w świecie. Kolejne upokorzenia prowadzą go na niebezpieczną drogę.' },
 { id: 'matrix', title: 'Matrix', original: 'The Matrix', year: 1999, rating: 8.2, genres: ['Sci-Fi', 'Akcja'], director: 'Lana i Lilly Wachowski', duration: '2 godz. 16 min', description: 'Haker Neo odkrywa, że znany mu świat jest symulacją. Dołącza do buntowników, którzy walczą o wolność ludzkości.' },
 { id: 'avengers', title: 'Avengers', original: 'The Avengers', year: 2012, rating: 7.7, genres: ['Akcja', 'Sci-Fi', 'Przygodowy'], director: 'Joss Whedon', duration: '2 godz. 23 min', description: 'Najpotężniejsi bohaterowie Ziemi łączą siły, aby powstrzymać Lokiego i uratować świat przed inwazją.' },
 { id: 'avatar', title: 'Avatar', original: 'Avatar', year: 2009, rating: 7.6, genres: ['Akcja', 'Sci-Fi', 'Przygodowy', 'Fantasy'], director: 'James Cameron', duration: '2 godz. 42 min', description: 'Na odległej Pandorze Jake Sully poznaje kulturę Na’vi. Wkrótce musi wybrać między rozkazami a ochroną swojego nowego domu.' },
 { id: 'nemo', title: 'Gdzie jest Nemo', original: 'Finding Nemo', year: 2003, rating: 7.6, genres: ['Animacja', 'Familijny', 'Przygodowy'], director: 'Andrew Stanton', duration: '1 godz. 40 min', description: 'Gdy mały Nemo trafia do akwarium, jego tata Marlin wraz z zapominalską Dory przemierza ocean, by odnaleźć syna.' },
 { id: 'pulp-fiction', title: 'Pulp Fiction', original: 'Pulp Fiction', year: 1994, rating: 8.5, genres: ['Kryminał', 'Dramat'], director: 'Quentin Tarantino', duration: '2 godz. 34 min', description: 'Losy dwóch płatnych zabójców, boksera i żony gangstera splatają się w zaskakującej opowieści o podziemnym świecie Los Angeles.' },
 { id: 'interstellar', title: 'Interstellar', original: 'Interstellar', year: 2014, rating: 8.6, genres: ['Sci-Fi', 'Dramat', 'Przygodowy'], director: 'Christopher Nolan', duration: '2 godz. 49 min', description: 'Gdy Ziemia przestaje być domem dla ludzkości, grupa odkrywców wyrusza przez tunel czasoprzestrzenny w poszukiwaniu nowego świata.', quote: '„Miłość przekracza granice czasu i przestrzeni.”' },
 { id: 'fight-club', title: 'Podziemny krąg', original: 'Fight Club', year: 1999, rating: 8.4, genres: ['Dramat', 'Thriller'], director: 'David Fincher', duration: '2 godz. 19 min', description: 'Cierpiący na bezsenność pracownik korporacji poznaje charyzmatycznego Tylera Durdena. Razem zakładają tajny klub walki.' },
 { id: 'shawshank', title: 'Skazani na Shawshank', original: 'The Shawshank Redemption', year: 1994, rating: 9.3, genres: ['Dramat'], director: 'Frank Darabont', duration: '2 godz. 22 min', description: 'Niesłusznie skazany bankier Andy Dufresne trafia do więzienia Shawshank. Przyjaźń i nadzieja pozwalają mu zachować człowieczeństwo.' },
 { id: 'forrest-gump', title: 'Forrest Gump', original: 'Forrest Gump', year: 1994, rating: 8.8, genres: ['Dramat', 'Komedia'], director: 'Robert Zemeckis', duration: '2 godz. 22 min', description: 'Forrest Gump z niezwykłą szczerością przechodzi przez najważniejsze wydarzenia amerykańskiej historii, nie zapominając o swojej pierwszej miłości.' },
 { id: 'lotr', title: 'Władca Pierścieni: Drużyna Pierścienia', original: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001, rating: 8.8, genres: ['Fantasy', 'Przygodowy'], director: 'Peter Jackson', duration: '2 godz. 58 min', description: 'Frodo otrzymuje zadanie zniszczenia Jedynego Pierścienia. Wraz z drużyną wyrusza w podróż, od której zależy los Śródziemia.' },
 { id: 'gladiator', title: 'Gladiator', original: 'Gladiator', year: 2000, rating: 8.5, genres: ['Akcja', 'Dramat', 'Historyczny'], director: 'Ridley Scott', duration: '2 godz. 35 min', description: 'Rzymski generał Maximus, zdradzony przez następcę cesarza, staje się gladiatorem. Na arenie szuka sprawiedliwości i zemsty.' },
 { id: 'spirited-away', title: 'Spirited Away: W krainie bogów', original: 'Spirited Away', year: 2001, rating: 8.6, genres: ['Animacja', 'Fantasy', 'Familijny'], director: 'Hayao Miyazaki', duration: '2 godz. 5 min', description: 'Chihiro trafia do niezwykłej krainy duchów. Aby uratować rodziców, musi nauczyć się odwagi i odnaleźć własną siłę.' },
 { id: 'parasite', title: 'Parasite', original: '기생충', year: 2019, rating: 8.5, genres: ['Dramat', 'Thriller', 'Komedia'], director: 'Bong Joon-ho', duration: '2 godz. 12 min', description: 'Uboga rodzina Kimów stopniowo przenika do życia zamożnych Parków. Gdy ich starannie zaplanowany układ zaczyna pękać, pozornie niewinna historia zmienia się w pełen napięcia pojedynek klas społecznych.', quote: '„Wszystko trzyma się kłamstwa.”' },
];
export const movies: Movie[] = entries.map(movie => ({ ...movie, poster: movieImages[movie.id], backdrop: movieImages[`${movie.id}-backdrop`] }));
export const genres = ['Wszystkie', 'Akcja', 'Sci-Fi', 'Dramat', 'Kryminał', 'Thriller', 'Przygodowy', 'Animacja', 'Familijny', 'Fantasy', 'Biograficzny', 'Historyczny', 'Komedia'];
export type ListEntry = { movie_id: string; list_type: string };
export type CatalogueView = 'all' | 'watchlist' | 'favorite';
const normalize = (value: string) => value.toLocaleLowerCase('pl').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/ł/g, 'l');
export function filterMovies(query: string, genre: string, view: CatalogueView, lists: ListEntry[]) {
 const search = normalize(query.trim());
 return movies.filter(movie => (genre === 'Wszystkie' || movie.genres.includes(genre)) && (!search || normalize([movie.title, movie.original, movie.director, ...movie.genres].join(' ')).includes(search)) && (view === 'all' || lists.some(entry => entry.movie_id === movie.id && entry.list_type === view)));
}