import { movieImages } from './movie-images';

export type Movie = { id: string; title: string; original: string; year: number; rating: number; genres: string[]; director: string; duration: string; description: string; quote?: string; poster: string; backdrop?: string };
const entries: Omit<Movie, 'poster' | 'backdrop'>[] = [
 { id: 'inception', title: 'Incepcja', original: 'Inception', year: 2010, rating: 8.4, genres: ['Sci-Fi', 'Akcja', 'Thriller'], director: 'Christopher Nolan', duration: '2 godz. 28 min', description: 'Dom Cobb potrafi kraść tajemnice z ludzkiej podświadomości. Tym razem musi dokonać czegoś niemożliwego: zaszczepić w umyśle nową ideę.', quote: '„Twój umysł jest miejscem zbrodni.”' },
 { id: 'dark-knight', title: 'Mroczny Rycerz', original: 'The Dark Knight', year: 2008, rating: 8.5, genres: ['Akcja', 'Kryminał', 'Dramat'], director: 'Christopher Nolan', duration: '2 godz. 32 min', description: 'Batman, porucznik Gordon i Harvey Dent próbują oczyścić Gotham z przestępczości. Ich plany burzy nieprzewidywalny Joker.' },
 { id: 'dark-knight-rises', title: 'Mroczny Rycerz Powstaje', original: 'The Dark Knight Rises', year: 2012, rating: 8, genres: ['Akcja', 'Thriller', 'Dramat'], director: 'Christopher Nolan', duration: '2 godz. 44 min', description: 'Osiem lat po zniknięciu Batmana Gotham staje w obliczu nowego zagrożenia. Bruce Wayne musi powrócić, by zmierzyć się z Bane’em.' },
 { id: 'joker', title: 'Joker', original: 'Joker', year: 2019, rating: 8.2, genres: ['Dramat', 'Kryminał', 'Thriller'], director: 'Todd Phillips', duration: '2 godz. 2 min', description: 'Arthur Fleck, samotny komik z Gotham, próbuje znaleźć swoje miejsce w świecie. Kolejne upokorzenia prowadzą go na niebezpieczną drogę.' },
 { id: 'matrix', title: 'Matrix', original: 'The Matrix', year: 1999, rating: 8.2, genres: ['Sci-Fi', 'Akcja'], director: 'Lana i Lilly Wachowski', duration: '2 godz. 16 min', description: 'Haker Neo odkrywa, że znany mu świat jest symulacją. Dołącza do buntowników, którzy walczą o wolność ludzkości.' },
 { id: 'avengers', title: 'Avengers', original: 'The Avengers', year: 2012, rating: 7.7, genres: ['Akcja', 'Sci-Fi', 'Przygodowy'], director: 'Joss Whedon', duration: '2 godz. 23 min', description: 'Najpotężniejsi bohaterowie Ziemi łączą siły, aby powstrzymać Lokiego i uratować świat przed inwazją.' },
 { id: 'avengers-ultron', title: 'Avengers: Czas Ultrona', original: 'Avengers: Age of Ultron', year: 2015, rating: 7.3, genres: ['Akcja', 'Sci-Fi', 'Przygodowy'], director: 'Joss Whedon', duration: '2 godz. 21 min', description: 'Gdy program ochrony świata, Ultron, wymyka się spod kontroli, Avengers muszą połączyć siły, by powstrzymać sztuczną inteligencję przed zniszczeniem ludzkości.' },
 { id: 'avengers-infinity-war', title: 'Avengers: Wojna bez granic', original: 'Avengers: Infinity War', year: 2018, rating: 8.4, genres: ['Akcja', 'Sci-Fi', 'Przygodowy'], director: 'Anthony i Joe Russo', duration: '2 godz. 29 min', description: 'Thanos przemierza galaktykę, zbierając Kamienie Nieskończoności. Avengers i ich sojusznicy stają do ostatecznego starcia o los wszechświata.', quote: '„Jestem nieuchronny.”' },
 { id: 'avengers-endgame', title: 'Avengers: Koniec gry', original: 'Avengers: Endgame', year: 2019, rating: 8.4, genres: ['Akcja', 'Sci-Fi', 'Przygodowy'], director: 'Anthony i Joe Russo', duration: '3 godz. 1 min', description: 'Po zniszczeniu połowy życia we wszechświecie pozostali Avengers szukają sposobu, by cofnąć czyny Thanosa i przywrócić zaginionych.', quote: '„Avengers, do boju.”' },
 { id: 'avatar', title: 'Avatar', original: 'Avatar', year: 2009, rating: 7.6, genres: ['Akcja', 'Sci-Fi', 'Przygodowy', 'Fantasy'], director: 'James Cameron', duration: '2 godz. 42 min', description: 'Na odległej Pandorze Jake Sully poznaje kulturę Na’vi. Wkrótce musi wybrać między rozkazami a ochroną swojego nowego domu.' },
 { id: 'nemo', title: 'Gdzie jest Nemo', original: 'Finding Nemo', year: 2003, rating: 7.6, genres: ['Animacja', 'Familijny', 'Przygodowy'], director: 'Andrew Stanton', duration: '1 godz. 40 min', description: 'Gdy mały Nemo trafia do akwarium, jego tata Marlin wraz z zapominalską Dory przemierza ocean, by odnaleźć syna.' },
 { id: 'pulp-fiction', title: 'Pulp Fiction', original: 'Pulp Fiction', year: 1994, rating: 8.5, genres: ['Kryminał', 'Dramat'], director: 'Quentin Tarantino', duration: '2 godz. 34 min', description: 'Losy dwóch płatnych zabójców, boksera i żony gangstera splatają się w zaskakującej opowieści o podziemnym świecie Los Angeles.' },
 { id: 'interstellar', title: 'Interstellar', original: 'Interstellar', year: 2014, rating: 8.6, genres: ['Sci-Fi', 'Dramat', 'Przygodowy'], director: 'Christopher Nolan', duration: '2 godz. 49 min', description: 'Gdy Ziemia przestaje być domem dla ludzkości, grupa odkrywców wyrusza przez tunel czasoprzestrzenny w poszukiwaniu nowego świata.', quote: '„Miłość przekracza granice czasu i przestrzeni.”' },
 { id: 'fight-club', title: 'Podziemny krąg', original: 'Fight Club', year: 1999, rating: 8.4, genres: ['Dramat', 'Thriller'], director: 'David Fincher', duration: '2 godz. 19 min', description: 'Cierpiący na bezsenność pracownik korporacji poznaje charyzmatycznego Tylera Durdena. Razem zakładają tajny klub walki.' },
 { id: 'shawshank', title: 'Skazani na Shawshank', original: 'The Shawshank Redemption', year: 1994, rating: 9.3, genres: ['Dramat'], director: 'Frank Darabont', duration: '2 godz. 22 min', description: 'Niesłusznie skazany bankier Andy Dufresne trafia do więzienia Shawshank. Przyjaźń i nadzieja pozwalają mu zachować człowieczeństwo.' },
 { id: 'forrest-gump', title: 'Forrest Gump', original: 'Forrest Gump', year: 1994, rating: 8.8, genres: ['Dramat', 'Komedia'], director: 'Robert Zemeckis', duration: '2 godz. 22 min', description: 'Forrest Gump z niezwykłą szczerością przechodzi przez najważniejsze wydarzenia amerykańskiej historii, nie zapominając o swojej pierwszej miłości.' },
 { id: 'lotr', title: 'Władca Pierścieni: Drużyna Pierścienia', original: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001, rating: 8.8, genres: ['Fantasy', 'Przygodowy'], director: 'Peter Jackson', duration: '2 godz. 58 min', description: 'Frodo otrzymuje zadanie zniszczenia Jedynego Pierścienia. Wraz z drużyną wyrusza w podróż, od której zależy los Śródziemia.' },
 { id: 'gladiator', title: 'Gladiator', original: 'Gladiator', year: 2000, rating: 8.5, genres: ['Akcja', 'Dramat', 'Historyczny'], director: 'Ridley Scott', duration: '2 godz. 35 min', description: 'Rzymski generał Maximus, zdradzony przez następcę cesarza, staje się gladiatorem. Na arenie szuka sprawiedliwości i zemsty.' },
 { id: 'spirited-away', title: 'Spirited Away: W krainie bogów', original: 'Spirited Away', year: 2001, rating: 8.6, genres: ['Animacja', 'Fantasy', 'Familijny'], director: 'Hayao Miyazaki', duration: '2 godz. 5 min', description: 'Chihiro trafia do niezwykłej krainy duchów. Aby uratować rodziców, musi nauczyć się odwagi i odnaleźć własną siłę.' },
 { id: 'parasite', title: 'Parasite', original: '기생충', year: 2019, rating: 8.5, genres: ['Dramat', 'Thriller', 'Komedia'], director: 'Bong Joon-ho', duration: '2 godz. 12 min', description: 'Uboga rodzina Kimów stopniowo przenika do życia zamożnych Parków. Gdy ich starannie zaplanowany układ zaczyna pękać, pozornie niewinna historia zmienia się w pełen napięcia pojedynek klas społecznych.', quote: '„Wszystko trzyma się kłamstwa.”' },
 { id: 'top-gun', title: 'Top Gun', original: 'Top Gun', year: 1986, rating: 6.9, genres: ['Akcja', 'Dramat'], director: 'Tony Scott', duration: '1 godz. 50 min', description: 'Pilot Pete „Maverick” Mitchell trafia do elitarnej szkoły lotnictwa marynarki wojennej, gdzie rywalizuje o miano najlepszego.' },
 { id: 'top-gun-maverick', title: 'Top Gun: Maverick', original: 'Top Gun: Maverick', year: 2022, rating: 8.2, genres: ['Akcja', 'Dramat'], director: 'Joseph Kosinski', duration: '2 godz. 11 min', description: 'Po ponad trzydziestu latach służby Maverick szkoli młodych pilotów do niebezpiecznej misji, wśród nich syna swojego zmarłego przyjaciela.', quote: '„Nie myśl, po prostu działaj.”' },
 { id: 'dune', title: 'Diuna', original: 'Dune', year: 2021, rating: 8, genres: ['Sci-Fi', 'Przygodowy', 'Dramat'], director: 'Denis Villeneuve', duration: '2 godz. 35 min', description: 'Paul Atryda przybywa na pustynną planetę Arrakis, najcenniejsze miejsce w galaktyce, gdzie jego rodzina staje się celem zdrady.' },
 { id: 'oppenheimer', title: 'Oppenheimer', original: 'Oppenheimer', year: 2023, rating: 8.3, genres: ['Biograficzny', 'Dramat', 'Historyczny'], director: 'Christopher Nolan', duration: '3 godz.', description: 'Historia J. Roberta Oppenheimera, fizyka, który pokierował pracami nad bombą atomową i zmienił świat na zawsze.' },
 { id: 'titanic', title: 'Titanic', original: 'Titanic', year: 1997, rating: 7.9, genres: ['Dramat', 'Historyczny'], director: 'James Cameron', duration: '3 godz. 14 min', description: 'Na pokładzie słynnego liniowca arystokratka Rose zakochuje się w ubogim artyście Jacku. Ich miłość zostaje wystawiona na próbę przez katastrofę.' },
 { id: 'django-unchained', title: 'Django', original: 'Django Unchained', year: 2012, rating: 8.5, genres: ['Dramat', 'Akcja'], director: 'Quentin Tarantino', duration: '2 godz. 45 min', description: 'Wyzwolony niewolnik Django łączy siły z łowcą nagród, by odbić żonę z rąk okrutnego plantatora.' },
 { id: 'whiplash', title: 'Whiplash', original: 'Whiplash', year: 2014, rating: 8.5, genres: ['Dramat'], director: 'Damien Chazelle', duration: '1 godz. 46 min', description: 'Młody perkusista trafia pod skrzydła bezwzględnego nauczyciela, który pcha go do granic możliwości.' },
 { id: 'la-la-land', title: 'La La Land', original: 'La La Land', year: 2016, rating: 8, genres: ['Komedia', 'Dramat'], director: 'Damien Chazelle', duration: '2 godz. 8 min', description: 'Aspirująca aktorka i pianista jazzowy zakochują się w Los Angeles, próbując jednocześnie spełnić swoje marzenia.' },
 { id: 'godfather', title: 'Ojciec chrzestny', original: 'The Godfather', year: 1972, rating: 9.2, genres: ['Kryminał', 'Dramat'], director: 'Francis Ford Coppola', duration: '2 godz. 55 min', description: 'Starzejący się patriarcha mafijnej rodziny Corleone przekazuje władzę niechętnemu synowi Michaelowi.' },
 { id: 'jurassic-park', title: 'Park Jurajski', original: 'Jurassic Park', year: 1993, rating: 8.2, genres: ['Sci-Fi', 'Przygodowy'], director: 'Steven Spielberg', duration: '2 godz. 7 min', description: 'Na wyspie, gdzie ożywiono dinozaury, awaria systemów zamienia wizytę naukowców w walkę o przetrwanie.' },
 { id: 'back-to-the-future', title: 'Powrót do przyszłości', original: 'Back to the Future', year: 1985, rating: 8.5, genres: ['Sci-Fi', 'Komedia', 'Przygodowy'], director: 'Robert Zemeckis', duration: '1 godz. 56 min', description: 'Nastolatek Marty McFly przypadkiem cofa się do 1955 roku wehikułem czasu i musi zadbać, by jego rodzice się poznali.' },
 { id: 'spiderman-brand-new-day', title: 'Spider-Man: Brand New Day', original: 'Spider-Man: Brand New Day', year: 2026, rating: 8.4, genres: ['Akcja', 'Sci-Fi', 'Przygodowy'], director: 'Destin Daniel Cretton', duration: '2 godz. 20 min', description: 'Peter Parker próbuje odnaleźć się w nowej rzeczywistości Nowego Jorku, gdy na ulicach pojawia się nowe, niebezpieczne zagrożenie.', quote: '„Z wielką siłą wiąże się wielka odpowiedzialność.”' },
  { id: 'shrek', title: 'Shrek', original: 'Shrek', year: 2001, rating: 7.9, genres: ['Animacja', 'Komedia', 'Familijny', 'Przygodowy'], director: 'Andrew Adamson, Vicky Jenson', duration: '1 godz. 30 min', description: 'Zielony ogr Shrek wyrusza na misję uwolnienia księżniczki Fiony ze szponów smoka, aby odzyskać spokój na swoim bagnie.', quote: '„Ogry są jak cebula.”' },
  { id: 'harry-potter', title: 'Harry Potter i Kamień Filozoficzny', original: "Harry Potter and the Philosopher's Stone", year: 2001, rating: 7.6, genres: ['Fantasy', 'Przygodowy', 'Familijny'], director: 'Chris Columbus', duration: '2 godz. 32 min', description: 'W dniu jedenastych urodzin Harry Potter dowiaduje się, że jest czarodziejem, i rozpoczyna naukę w Hogwarcie.' },
  { id: 'dune-part-two', title: 'Diuna: Część druga', original: 'Dune: Part Two', year: 2024, rating: 8.5, genres: ['Sci-Fi', 'Przygodowy', 'Dramat', 'Akcja'], director: 'Denis Villeneuve', duration: '2 godz. 46 min', description: 'Paul Atryda jednoczy się z Chani i Fremenami, szukając zemsty na tych, którzy zniszczyli jego rodzinę.' },
  { id: 'spider-man-no-way-home', title: 'Spider-Man: Bez drogi do domu', original: 'Spider-Man: No Way Home', year: 2021, rating: 8.2, genres: ['Akcja', 'Sci-Fi', 'Przygodowy'], director: 'Jon Watts', duration: '2 godz. 28 min', description: 'Po ujawnieniu tożsamości Peter Parker prosi Doktora Strange’a o pomoc, co przypadkowo otwiera multiwersum.' },
  { id: 'the-batman', title: 'Batman', original: 'The Batman', year: 2022, rating: 7.8, genres: ['Akcja', 'Kryminał', 'Dramat'], director: 'Matt Reeves', duration: '2 godz. 56 min', description: 'Gdy seryjny morderca bierze na cel elitę Gotham, Batman musi zanurzyć się w świat korupcji.', quote: '„Jestem zemstą.”' },
];
export const movies: Movie[] = entries.map(movie => {
 const poster = movieImages[movie.id];
 if (!poster) throw new Error(`Missing poster: ${movie.id}`);
 const backdrop = movieImages[`${movie.id}-backdrop`];
 return { ...movie, poster, ...(backdrop ? { backdrop } : {}) };
})
const trailers: Record<string, string> = { inception: 'YoHD9XEInc0', interstellar: 'zSWdZVtXT7E', 'dark-knight': 'EXeTwQWrcwY', 'dark-knight-rises': 'g8evyE9TuYk', matrix: 'vKQi3bBA1y8', parasite: '5xH0HfJHsaY', dune: '8g18jFHCLXk', oppenheimer: 'uYPbbksJxIg', 'top-gun': 'xa_z57UatDY', 'top-gun-maverick': 'giXco2jaZ_4', joker: 'zAGVQLHvwOY', avengers: 'eOrNdBpGMv8', 'avengers-ultron': 'tmeOjFno6Do', 'avengers-infinity-war': '6ZfuNTqbHE8', 'avengers-endgame': 'TcMBFSGVi1c', avatar: '5PSNL1qE6VY', nemo: '9oQ628Seb9w', 'pulp-fiction': 's7EdQ4FqbhY', 'fight-club': 'qtRKdVHc-cE', shawshank: '6hB3S9bIaco', 'forrest-gump': 'bLvqoHBptjg', lotr: 'V75dMMIW2B4', gladiator: 'owK1qxDselE', 'spirited-away': 'ByXuk9QqQkk', titanic: 'kVrqfYjkTdQ', 'django-unchained': '0fUCuvNlOCg', whiplash: '7d_jQycdQGo', 'la-la-land': '0pdqf4P9MB8', godfather: 'UaVTIH8mujA', 'jurassic-park': 'lc0UehYemQA', 'back-to-the-future': 'qvsgGtivCgs', 'spiderman-brand-new-day': '8TZMtslA3UY', shrek: 'CwXOrWvPBPk', 'harry-potter': 'VyHV0BRtdxo', 'dune-part-two': 'Way9Dexny3w', 'spider-man-no-way-home': 'JfVOs4VSpmA', 'the-batman': 'mqqft2x_Aa4' };
, 'jurassic-park': 'lc0UehYemQA', 'back-to-the-future': 'qvsgGtivCgs', 'spiderman-brand-new-day': '8TZMtslA3UY', shrek: 'CwXOrWvPBPk', 'harry-potter': 'VyHV0BRtdxo', 'dune-part-two': 'Way9Dexny3w', 'spider-man-no-way-home': 'JfVOs4VSpmA', 'the-batman': 'mqqft2x_Aa4' };
export const trailerId = (id: string): string | undefined => trailers[id];
export const trailerSearchUrl = (m: Movie) => `https://www.youtube.com/results?search_query=${encodeURIComponent(`${m.original} ${m.year} official trailer`)}`;
export const genres = ['Wszystkie', 'Akcja', 'Sci-Fi', 'Dramat', 'Kryminał', 'Thriller', 'Przygodowy', 'Animacja', 'Familijny', 'Fantasy', 'Biograficzny', 'Historyczny', 'Komedia'];
export type ListEntry = { movie_id: string; list_type: string };
export type CatalogueView = 'all' | 'watchlist' | 'favorite' | 'rated';
const normalize = (value: string) => value.toLocaleLowerCase('pl').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/ł/g, 'l');
export function weekNumber(date: Date): number {
 const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
 const day = d.getUTCDay() || 7;
 d.setUTCDate(d.getUTCDate() + 4 - day);
 const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
 return d.getUTCFullYear() * 100 + Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
}
export function weeklyMovies(date: Date, count = 4): Movie[] {
 const start = (weekNumber(date) * count) % movies.length;
 return Array.from({ length: count }, (_, i) => movies[(start + i) % movies.length]!);
}
export function filterMovies(query: string, genre: string, view: CatalogueView, lists: ListEntry[]) {
 const search = normalize(query.trim());
 return movies.filter(movie => (genre === 'Wszystkie' || movie.genres.includes(genre)) && (!search || normalize([movie.title, movie.original, movie.director, ...movie.genres].join(' ')).includes(search)) && (view === 'all' || lists.some(entry => entry.movie_id === movie.id && entry.list_type === view)));
}